const fs = require('fs');
const path = require('path');

const file = path.join(__dirname, '../public/data/verses/gen.1.10.json');
let data = JSON.parse(fs.readFileSync(file, 'utf8'));

const correctHebrewTokens = [
  {
    "id": "gen.1.10.h1",
    "lang": "hebrew",
    "langPt": "Hebraico",
    "langEn": "Hebrew",
    "surface": "וַיִּקְרָא",
    "transliteration": "Vayikra",
    "lemma": "קָרָא",
    "strong": "H7121",
    "bdb": "to call, to name",
    "morph": "V-Qal-Wayyq-3ms",
    "manuscript": "Hebraico: Codex Leningradensis (B19A), tradição massorética (MT)",
    "manuscriptEn": "Hebrew: Codex Leningradensis (B19A), Masoretic tradition (MT)",
    "ptLiteralWord": "E chamou",
    "enLiteralWord": "And he called",
    "explanation": "E chamou",
    "explanationEn": "And he called"
  },
  {
    "id": "gen.1.10.h2",
    "lang": "hebrew",
    "langPt": "Hebraico",
    "langEn": "Hebrew",
    "surface": "אֱלֹהִים",
    "transliteration": "Elohim",
    "lemma": "אֱלֹהִים",
    "strong": "H430",
    "morph": "N-mp",
    "manuscript": "Hebraico: Codex Leningradensis (B19A), tradição massorética (MT)",
    "manuscriptEn": "Hebrew: Codex Leningradensis (B19A), Masoretic tradition (MT)",
    "ptLiteralWord": "Deus",
    "enLiteralWord": "God",
    "explanation": "Deus (plural majestático)",
    "explanationEn": "God (majestic plural)"
  },
  {
    "id": "gen.1.10.h3",
    "lang": "hebrew",
    "langPt": "Hebraico",
    "langEn": "Hebrew",
    "surface": "לַיַּבָּשָׁה",
    "transliteration": "layabashah",
    "lemma": "יַבָּשָׁה",
    "strong": "H3004",
    "bdb": "dry land, dry ground",
    "morph": "Prep-l | Art | N-fs",
    "manuscript": "Hebraico: Codex Leningradensis (B19A), tradição massorética (MT)",
    "manuscriptEn": "Hebrew: Codex Leningradensis (B19A), Masoretic tradition (MT)",
    "ptLiteralWord": "à porção seca",
    "enLiteralWord": "to the dry land",
    "explanation": "À porção seca / Ao seco",
    "explanationEn": "To the dry land"
  },
  {
    "id": "gen.1.10.h4",
    "lang": "hebrew",
    "langPt": "Hebraico",
    "langEn": "Hebrew",
    "surface": "אֶרֶץ",
    "transliteration": "eretz",
    "lemma": "אֶרֶץ",
    "strong": "H776",
    "bdb": "earth, land",
    "morph": "N-fs",
    "manuscript": "Hebraico: Codex Leningradensis (B19A), tradição massorética (MT)",
    "manuscriptEn": "Hebrew: Codex Leningradensis (B19A), Masoretic tradition (MT)",
    "ptLiteralWord": "terra;",
    "enLiteralWord": "earth;",
    "explanation": "Terra",
    "explanationEn": "Earth / Land"
  },
  {
    "id": "gen.1.10.h5",
    "lang": "hebrew",
    "langPt": "Hebraico",
    "langEn": "Hebrew",
    "surface": "וּלְמִקְוֵה",
    "transliteration": "ulemikveh",
    "lemma": "מִקְוֶה",
    "strong": "H4723",
    "bdb": "gathering, collected mass",
    "morph": "Conj-w | Prep-l | N-msc",
    "manuscript": "Hebraico: Codex Leningradensis (B19A), tradição massorética (MT)",
    "manuscriptEn": "Hebrew: Codex Leningradensis (B19A), Masoretic tradition (MT)",
    "ptLiteralWord": "e ao ajuntamento",
    "enLiteralWord": "and to the gathering",
    "explanation": "E à coleção / ajuntamento",
    "explanationEn": "And to the gathering"
  },
  {
    "id": "gen.1.10.h6",
    "lang": "hebrew",
    "langPt": "Hebraico",
    "langEn": "Hebrew",
    "surface": "הַמַּיִם",
    "transliteration": "hamayim",
    "lemma": "מַיִם",
    "strong": "H4325",
    "bdb": "water, waters",
    "morph": "Art | N-mp",
    "manuscript": "Hebraico: Codex Leningradensis (B19A), tradição massorética (MT)",
    "manuscriptEn": "Hebrew: Codex Leningradensis (B19A), Masoretic tradition (MT)",
    "ptLiteralWord": "das águas",
    "enLiteralWord": "of the waters",
    "explanation": "As águas",
    "explanationEn": "The waters"
  },
  {
    "id": "gen.1.10.h7",
    "lang": "hebrew",
    "langPt": "Hebraico",
    "langEn": "Hebrew",
    "surface": "קָרָא",
    "transliteration": "qara",
    "lemma": "קָרָא",
    "strong": "H7121",
    "bdb": "to call, to name",
    "morph": "V-Qal-Perf-3ms",
    "manuscript": "Hebraico: Codex Leningradensis (B19A), tradição massorética (MT)",
    "manuscriptEn": "Hebrew: Codex Leningradensis (B19A), Masoretic tradition (MT)",
    "ptLiteralWord": "chamou",
    "enLiteralWord": "he called",
    "explanation": "Ele chamou",
    "explanationEn": "He called"
  },
  {
    "id": "gen.1.10.h8",
    "lang": "hebrew",
    "langPt": "Hebraico",
    "langEn": "Hebrew",
    "surface": "יַמִּים",
    "transliteration": "yamim",
    "lemma": "יָם",
    "strong": "H3220",
    "bdb": "sea",
    "morph": "N-mp",
    "manuscript": "Hebraico: Codex Leningradensis (B19A), tradição massorética (MT)",
    "manuscriptEn": "Hebrew: Codex Leningradensis (B19A), Masoretic tradition (MT)",
    "ptLiteralWord": "mares;",
    "enLiteralWord": "seas;",
    "explanation": "Mares",
    "explanationEn": "Seas"
  },
  {
    "id": "gen.1.10.h9",
    "lang": "hebrew",
    "langPt": "Hebraico",
    "langEn": "Hebrew",
    "surface": "וַיַּרְא",
    "transliteration": "vayar",
    "lemma": "רָאָה",
    "strong": "H7200",
    "bdb": "to see",
    "morph": "V-Qal-Wayyq-3ms",
    "manuscript": "Hebraico: Codex Leningradensis (B19A), tradição massorética (MT)",
    "manuscriptEn": "Hebrew: Codex Leningradensis (B19A), Masoretic tradition (MT)",
    "ptLiteralWord": "e viu",
    "enLiteralWord": "and he saw",
    "explanation": "E viu",
    "explanationEn": "And he saw"
  },
  {
    "id": "gen.1.10.h10",
    "lang": "hebrew",
    "langPt": "Hebraico",
    "langEn": "Hebrew",
    "surface": "אֱלֹהִים",
    "transliteration": "Elohim",
    "lemma": "אֱלֹהִים",
    "strong": "H430",
    "morph": "N-mp",
    "manuscript": "Hebraico: Codex Leningradensis (B19A), tradição massorética (MT)",
    "manuscriptEn": "Hebrew: Codex Leningradensis (B19A), Masoretic tradition (MT)",
    "ptLiteralWord": "Deus",
    "enLiteralWord": "God",
    "explanation": "Deus (plural majestático)",
    "explanationEn": "God (majestic plural)"
  },
  {
    "id": "gen.1.10.h11",
    "lang": "hebrew",
    "langPt": "Hebraico",
    "langEn": "Hebrew",
    "surface": "כִּי",
    "transliteration": "ki",
    "lemma": "כִּי",
    "strong": "H3588",
    "bdb": "that, because",
    "morph": "Conj",
    "manuscript": "Hebraico: Codex Leningradensis (B19A), tradição massorética (MT)",
    "manuscriptEn": "Hebrew: Codex Leningradensis (B19A), Masoretic tradition (MT)",
    "ptLiteralWord": "que era",
    "enLiteralWord": "that it was",
    "explanation": "Que / Porque",
    "explanationEn": "That / Because"
  },
  {
    "id": "gen.1.10.h12",
    "lang": "hebrew",
    "langPt": "Hebraico",
    "langEn": "Hebrew",
    "surface": "טוֹב",
    "transliteration": "tov",
    "lemma": "טוֹב",
    "strong": "H2896",
    "bdb": "good, pleasant",
    "morph": "Adj-ms",
    "manuscript": "Hebraico: Codex Leningradensis (B19A), tradição massorética (MT)",
    "manuscriptEn": "Hebrew: Codex Leningradensis (B19A), Masoretic tradition (MT)",
    "ptLiteralWord": "bom.",
    "enLiteralWord": "good.",
    "explanation": "Bom",
    "explanationEn": "Good"
  }
];

const newTokens = [];
for (const t of data.tokens) {
  if (t.lang !== 'hebrew') {
    newTokens.push(t);
  }
}
data.tokens = [...correctHebrewTokens, ...newTokens];

fs.writeFileSync(file, JSON.stringify(data, null, 4));
console.log('Fixed gen.1.10.json');
